In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
l=[1,2,3,4,5,6,7,8,9,10]

In [3]:
print(np.array(l))

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
l=[[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]]

In [5]:
arr=np.array(l)

In [6]:
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18]]])

In [7]:
arr.shape

(1, 1, 18)

In [8]:
arr=np.reshape(arr,(18,1,1))

In [9]:
arr.shape

(18, 1, 1)

In [11]:
arr[3:8,:,:]

array([[[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])