In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
l=[1,2,3,4,5,6,7,8,9,10]

In [3]:
print(np.array(l))

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
l=[[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]]

In [5]:
arr=np.array(l)

In [6]:
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18]]])

In [7]:
arr.shape

(1, 1, 18)

In [8]:
arr=np.reshape(arr,(18,1,1))

In [9]:
arr.shape

(18, 1, 1)

In [11]:
arr[3:8,:,:]

array([[[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [12]:
l=[1,2,3,4,5,6,7,8]

In [13]:
arr=np.array(l)

In [14]:
l2= l*2

In [15]:
l2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
arr2 =arr*2

In [18]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [19]:
arr2.shape

(8,)

In [20]:
arr3=arr*2.5

In [21]:
arr3

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [22]:
l4 =l2 +l

In [23]:
l4

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
arr4=arr2 + arr3

In [25]:
arr4

array([ 4.5,  9. , 13.5, 18. , 22.5, 27. , 31.5, 36. ])